apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: k8s-multi-com-tls
spec:
  secretName: k8s-multi-com-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: yaya626.com
  dnsNames:
    - yaya626.com
    - www.yaya626.com
  acme: 
    config:
      - http01:
          ingressClass: nginx
        domains:
          - yaya626.com
          - www.yaya626.com
  