apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: k8s-multi-com-tls
  namespace: default
spec:
  secretName: k8s-multi-com-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - k8s-multi.com
    - www.k8s-multi.com