apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: 'reubenaborchie85@gmail'
    privateKeySecretRef:
      name: letsencrypt-prod
    https01: {}
